### PR TITLE
Bot added for mediawiki tasks

### PR DESCRIPTION
**Pull request by apexkid**
Currently syndicating only ratings for main extension page. Will add support for more data in subpage after finalization of template.

### CODE REVIEW

**Comment by hexmode** [comment]
@apexkid Could you respond to the issues @thingles has pointed out?  Will you be able to address them?

**Comment by apexkid** [comment]
@hexmode  I am fixing them. I need a little help from @thingles. 
First, I suppose the error log shows error in mworg_bee. I think this is because there are no login credentials provided for it. Currently there is no account for it on mediawiki so please create it and add details to config file.
Second, I wrote the function with return 0 just to structure the code in respect to future scope but i will remove it if it looks unconventional.

**Comment by apexkid** [comment]
@thingles I still find error in mworg_bee. Please tell me how this has to be fixed. I think its just because of missing login credentials in config file. Also I fixed the issues you mentioned earlier. Please review again. Thanks.

**Comment by jthingelstad** [comment]
I just noticed this PR is against `master`. Can you change it to `develop`?

**Comment by jthingelstad** [comment]
@apexkid Couple of things.
- I created a branch `feature/gsoc`. Please do your pull request against that branch. Ignore request above to pull against `develop`. I’m not sure you can _move_ a pull request to a different branch. I think you may have to abandon this one and do a new pull. Plus, you'll want to rebase off of the `feature/gsoc` branch anyway.
- I closed #196 so Travis-CI will now be able to login as [WikiApiary on MediaWiki.org](https://www.mediawiki.org/wiki/User:WikiApiary). This account has bot privileges thanks to @hexmode. I assume you will want to watch [contributions](https://www.mediawiki.org/wiki/Special:Contributions/WikiApiary) to see how it goes. The environment variable is `MWORGBEE`.
- I modified `connect_wikiapiary.py` to allow the simplemediawiki objects to still be created even if you don't have a password. At least that way only unit tests that attempt writes will fail. This should allow you, even without passwords locally, to run nosetests and see some tests pass.

**Comment by jthingelstad** [comment]
Replaced by #198.

**Pull request closed without merging**
